In [23]:
import pandas as pd

In [24]:
pd.__version__

'2.2.3'

In [25]:
dict_medidas = {'idade': [15, 18, 25, 25, 40, 55, 58, 60, 80], 'altura': [160, 162, 165, 168, 172, 174, 174, 174, 176]}

In [26]:
dict_medidas

{'idade': [15, 18, 25, 25, 40, 55, 58, 60, 80],
 'altura': [160, 162, 165, 168, 172, 174, 174, 174, 176]}

In [27]:
df_medidas = pd.DataFrame(dict_medidas)

In [28]:
df_medidas

   idade  altura
0     15     160
1     18     162
2     25     165
3     25     168
4     40     172
5     55     174
6     58     174
7     60     174
8     80     176

# Medidas resumo

### Medidas de posição

In [29]:
# media
df_medidas['idade'].mean()

np.float64(41.77777777777778)

In [30]:
# mediana
df_medidas['idade'].median()

np.float64(40.0)

In [31]:
# moda
df_medidas['idade'].mode()

0    25
Name: idade, dtype: int64

In [32]:
# moda
df_medidas['altura'].mode()

0    174
Name: altura, dtype: int64

# Medidas de dispersão

In [33]:
# variancia
df_medidas['idade'].var()

np.float64(509.94444444444446)

In [34]:
# desvio padrao
df_medidas['idade'].std()

np.float64(22.58194952709895)

In [35]:
# coeficiente de variacao - idade
df_medidas['idade'].std() / df_medidas['idade'].mean() * 100

np.float64(54.05253876167302)

In [36]:
# coeficiente de variacao - altura
df_medidas['altura'].std() / df_medidas['altura'].mean() * 100

np.float64(3.4803552812368785)

# Medidas de forma

In [37]:
# assimetria da idade
df_medidas['idade'].skew()

np.float64(0.368108517895537)

In [41]:
# assimetria da altura
df_medidas['altura'].skew()

np.float64(-0.598486996170113)

In [42]:
# curtose da idade
df_medidas['idade'].kurtosis()

np.float64(-1.1344461075421046)

In [43]:
# curtose da altura
df_medidas['altura'].kurtosis()

np.float64(-1.3372641199913002)

In [44]:
# descreva
df_medidas.describe()

           idade      altura
count   9.000000    9.000000
mean   41.777778  169.444444
std    22.581950    5.897269
min    15.000000  160.000000
25%    25.000000  165.000000
50%    40.000000  172.000000
75%    58.000000  174.000000
max    80.000000  176.000000